name: Deploy APT Repository to GitHub Pages

on:
  workflow_run:
    workflows: ["Build and Release APT Package"]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download APT repository artifacts
        uses: actions/download-artifact@v4
        with:
          name: apt-repository
          path: ./apt-repo
          merge-multiple: false

      - name: Debug artifact contents
        run: |
          echo "Checking if apt-repo directory exists:"
          ls -la || echo "No files in current directory"

          echo "Checking apt-repo directory contents:"
          ls -la apt-repo/ || echo "apt-repo directory not found"

          echo "Checking for APT repository files:"
          find apt-repo/ -type f 2>/dev/null || echo "No files found in apt-repo"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './apt-repo'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
